version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  fluentd:
    image: gisjedi/scale-fluentd
    command: fluentd -vv -c /fluentd/etc/fluent.conf
    container_name: fluentd
    environment:
      - ELASTICSEARCH_URLS=http://elasticsearch:9200
    links:
      - elasticsearch
    ports:
      - 24220:24220
      - 24224:24224
